\c telpark

BEGIN;

DROP TABLE IF EXISTS tabla1;
DROP TABLE IF EXISTS tabla2;
DROP TABLE IF EXISTS tabla3;

CREATE TABLE IF NOT EXISTS tabla1(
    x REAL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS tabla2(
    y REAL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS tabla3(
    z REAL PRIMARY KEY
);

INSERT INTO tabla1 VALUES (30);
INSERT INTO tabla2 VALUES (40);
INSERT INTO tabla3 VALUES (50);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE tabla1, tabla2, tabla3 TO rol_usuario;
COMMIT;